const NOT_FOUND = new Set([
  "RELEASE_NOT_FOUND",
  "APPROVAL_NOT_FOUND",
  "ACTION_PACKAGE_NOT_FOUND",
  "VIDEO_RUN_NOT_FOUND"
]);

const CONFLICT = new Set([
  "APPROVAL_ALREADY_RESOLVED",
  "APPROVAL_EXPIRED",
  "PAYLOAD_MISMATCH",
  "INVALID_RELEASE_TRANSITION",
  "SUBMISSION_NOT_AUTHORIZED",
  "REVISION_EVIDENCE_REQUIRED",
  "CAPTION_VERSION_ALREADY_EXISTS",
  "VIDEO_RUN_ALREADY_EXISTS",
  "VIDEO_VERSION_CONFLICT",
  "VIDEO_PERSISTENCE_CONFLICT",
  "EXTERNAL_TASK_RECEIPT_REQUIRED",
  "EXTERNAL_TASK_RECEIPT_IMMUTABLE",
  "EXTERNAL_RESULT_RECEIPT_IMMUTABLE",
  "EXTERNAL_TASK_RECEIPT_CONFLICT",
  "QC_NOT_READY"
]);

const BAD_REQUEST = new Set([
  "EXTERNAL_CONFIRMATION_REQUIRED",
  "VERIFIED_PLATFORM_URL_REQUIRED",
  "VALID_SCHEDULE_DATE_REQUIRED",
  "PROVIDER_MISMATCH",
  "RELEASE_PACKAGE_INCOMPLETE",
  "RELEASE_NOT_PREPARED",
  "EXTERNAL_TASK_ID_REQUIRED",
  "CAPTIONS_REQUIRED",
  "TECHNICAL_METADATA_UNAVAILABLE",
  "CAPTION_LOCALE_REQUIRED",
  "EMPTY_CAPTION_TEXT",
  "OVERLAPPING_CAPTIONS"
]);

export function apiStatusForCode(code: string): number {
  if (NOT_FOUND.has(code)) return 404;
  if (CONFLICT.has(code)) return 409;
  if (
    BAD_REQUEST.has(code) ||
    code.startsWith("INVALID_") ||
    code.endsWith("_REQUIRED")
  ) {
    return 400;
  }
  return 500;
}
