export type ProjectState =
  | "IDEA"
  | "STRATEGY"
  | "WRITING"
  | "PRODUCTION"
  | "VOCALS"
  | "MIXING"
  | "MASTERING"
  | "SELECTED"
  | "QA"
  | "ASSET_GENERATION"
  | "METADATA"
  | "DISTRIBUTION_READY"
  | "APPROVAL"
  | "SCHEDULED"
  | "RELEASED"
  | "MONETIZING"
  | "ANALYZED"
  | "FAILED"
  | "ARCHIVED";

export const PROJECT_TRANSITIONS: Record<ProjectState, ProjectState[]> = {
  IDEA: ["STRATEGY", "WRITING", "FAILED"],
  STRATEGY: ["WRITING", "FAILED"],
  WRITING: ["PRODUCTION", "FAILED"],
  PRODUCTION: ["VOCALS", "FAILED"],
  VOCALS: ["MIXING", "FAILED"],
  MIXING: ["MASTERING", "FAILED"],
  MASTERING: ["SELECTED", "QA", "FAILED"],
  SELECTED: ["QA", "FAILED"],
  QA: ["ASSET_GENERATION", "WRITING", "PRODUCTION", "MIXING", "FAILED"],
  ASSET_GENERATION: ["METADATA", "FAILED"],
  METADATA: ["DISTRIBUTION_READY", "FAILED"],
  DISTRIBUTION_READY: ["APPROVAL", "FAILED"],
  APPROVAL: ["SCHEDULED", "DISTRIBUTION_READY", "FAILED"],
  SCHEDULED: ["RELEASED", "FAILED"],
  RELEASED: ["MONETIZING"],
  MONETIZING: ["ANALYZED"],
  ANALYZED: ["MONETIZING", "ARCHIVED"],
  FAILED: ["IDEA", "WRITING", "PRODUCTION", "ARCHIVED"],
  ARCHIVED: []
};

export function canProjectTransition(from: ProjectState, to: ProjectState): boolean {
  return PROJECT_TRANSITIONS[from]?.includes(to) ?? false;
}

export const PORTFOLIO_STATUS: Record<ProjectState, string> = {
  IDEA: "CONCEPT",
  STRATEGY: "CONCEPT",
  WRITING: "WRITING",
  PRODUCTION: "DEMO",
  VOCALS: "DEMO",
  MIXING: "DEMO",
  MASTERING: "DEMO",
  SELECTED: "SELECTED",
  QA: "QA",
  ASSET_GENERATION: "QA",
  METADATA: "QA",
  DISTRIBUTION_READY: "RELEASE_READY",
  APPROVAL: "RELEASE_READY",
  SCHEDULED: "RELEASE_READY",
  RELEASED: "PUBLISHED",
  MONETIZING: "PUBLISHED",
  ANALYZED: "PUBLISHED",
  FAILED: "EXCEPTION",
  ARCHIVED: "ARCHIVED"
};
